site_name: Cargosure
site_url: https://www.cargosure.co
site_description: Documentacion para plataforma web Cargosure
site_author: Juan Moreno
copyright: 'Copyright &copy; 2020'

nav:
    - Inicio: index.md
    - Tutoriales: 
        - Uso administrador: 'tutorial-manager.md'
        - Uso aseguradora: 'tutorial-insurancer.md'
        - Uso tomador: 'tutorial-taker.md'
        - Uso generador: 'tutorial-generator.md'
    - Nosotros: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'

theme:
    name: material
    language: es
    logo: img/logo.png
    favicon: img/favicon.ico
    custom_dir: overrides
    shortcuts:
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra_css:
  - stylesheets/extra.css

extra:
    version: 1.0