site_name: Cargosure
site_url: https://www.cargosure.co
site_description: Documentacion para plataforma web Cargosure
site_author: Juan Moreno
copyright: 'Copyright &copy; 2020'

nav:
    - Inicio: index.md
    - Tutoriales: 
        - Uso Administrador: 'tutorial-manager.md'
        - Uso Aseguradora: 'tutorial-insurancer.md'
        - Uso Intermediario: 'tutorial-intermediary.md'
        - Uso Tomador: 'tutorial-taker.md'
        - Uso Generador: 'tutorial-generator.md'
    - Nosotros: about.md

markdown_extensions:

    - admonition
    - toc:
        permalink: '#'
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde

theme:
    name: material
    language: es
    logo: img/logo.png
    favicon: img/favicon.ico
    custom_dir: overrides
    shortcuts:
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra_css:
  - stylesheets/extra.css

extra:
    version: 1.0